[package]
name = "mlxai"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
winres = "0.1.12"
structopt = "0.3.26"
serde_json = "1.0.125"
reqwest = { version = "0.12.7", features = ["json"] }
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }